eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation:  true
